### ISSUE TITLE
Pipeline issues

### ISSUE THREAD

**Issue by mcarvin8** [mcarvin8/xml-disassembler#1]
Having some issues when putting this into the pipeline for the first time. 

This runs fine for me locally when I run "pnpm tests" and confirm expected output for disassembled and reassembled XML files. 

@AllanOricil - Can you look at the job logs/ts config file and let me know if something looks off to you? I've had to modify the tsconfig file but I'm not sure if I did anything incorrectly. Also had to rename the package due to an existing xml transformer on NPM.

**Comment by AllanOricil** [comment]
@mcarvin8 you have to fix build errors. In your case there are a lot of TS errors. To avoid that in the future, do the same thing you did on the other project. Add a protection rule on your release branch to enforce PRs and status checks to pass. Then ensure a build and test automation runs on every commit pushed to any branch. Then only allow branches to be merged to your release branch if there are no build or test errors.

**Comment by mcarvin8** [comment]
This was be being a total newb with JS. When re-trying this on my work laptop which didn't have this originally, I traced it back to needing to install @types/node as a dev dependency. This is now testing fine in CI.
