### ISSUE TITLE
Add use cases on the README to justify the creation of this package

### ISSUE THREAD

**Issue by AllanOricil** [mcarvin8/xml-disassembler#2]
For example, you can get a huge XML file that is a pain in the ass to review when modified (eg. Custom Labels created by Vlocity), and then show how much easier it becomes after breaking it down into more xml files. 

Also, try to explain the trade-offs of using an XML diff algorithm and this package to decompose/compose XML files with the goal of simplifying PR reviews. I never tried any of these custom diff algorithms, so I can't say if they work better than just breaking XMLs into parts. If you ca expose a problem that this package solves better than those algorithms, then people could try it in their workflows.

It is important to mention that even if it is possible to use custom diff algorithms locally, I can't install them on third party git repositories, and I don't know if they use any that are specific for XML. I'm pretty sure that they don't, because I once tried to review a PR that had a huge custom labels file, generated by Vlocity, and it was a mess. I couldn't not figure out with ease which ones were added, or removed. I also can't remember if I was doing something wrong when exporting those metadata files. The best way I could find to simplify PR reviews  on that file was to manually append new custom labels at the end of it, and ignore the exported order that metadata api created. So, if you can show people that using your tool simplifies reviewing PRs containing huge XML files with lots of diffs, and that they can use it with Github, Gitlab, Bitbucket and other remote git repositories, I believe that this would be another reason for this package to exist.

**Comment by mcarvin8** [comment]
Some background info/justification and a screenshot was added to the README for this initial release, which is now on NPM.

Let me know if it makes sense to you.

**Comment by AllanOricil** [comment]
dope
